import pathlib
base = pathlib.Path(r"E:\github\dsh\projects\helloworld -unrealengine")
contents = {
 "Content/Weavers/BP_Weaver.uasset.README.md": "# BP_Weaver — Character Blueprint\n\n- **Parent**: ARiftWeaveCharacter (C++)\n- **Mesh**: MetaHuman-derived Weaver (ControlRig face + body, 4 LODs)\n- **Anims**: WeaverAnimInstance + MotionWarping (vault/pull)\n- **Cloth**: Chaos Cloth cloak, thread ribbons (wind + weave drag)\n- **VFX**: Niagara NS_WeaveTrail attached to hand socket\n\nTo rebuild: import MetaHuman to /Content/Weavers/MH_Weaver, retarget via IK Retargeter RTG_Weaver.\n",
 "Content/World/Biomes/ObsidianForge/README.md": "# Obsidian Forge — Biome\n\n- **Visual**: Black basalt, orange emissive lava, ash fog. Reference: Iceland + Monument Valley.\n- **Nanite**: All rock meshes Nanite (12M tris cliff -> HLOD). Not for foliage.\n- **Lumen**: Emissive lava is primary light; bounce is gameplay.\n- **Chaos**: Shatterable crust, forge hammer puzzle (GC_ObsidianCrust).\n- **Data Layer**: DL_Obsidian (World Partition, cell 32m, range 64k)\n- **POIs**: 18 — Crucible, Cooling Towers, Forgefather Memory Echo\n",
 "Content/World/Biomes/Frostvein/README.md": "# Frostvein Tundra — Biome\n\n- **Visual**: Whiteout plains, cyan crystal caves, aurora.\n- **Nanite**: Ice cave walls Nanite with displacement; snow uses RVT + PCG.\n- **Lumen**: Aurora + crystal refraction — light-as-resource.\n- **MassAI**: 2000 frost-elk herd (StateTree ST_ElkHerd).\n- **Data Layer**: DL_Frostvein\n- **POIs**: 22 — Thaw Child shrine, Crystal Harp, Migratory Trail\n",
 "Content/World/Biomes/LuminousCanopy/README.md": "# Luminous Canopy — Biome\n\n- **Visual**: Bioluminescent jungle, floating seeds, spore fog.\n- **Nanite**: Trunks/rocks Nanite; leaves are cards + WPO wind.\n- **Niagara**: NS_SporeCloud, NS_VineGrowth, NS_CanopyFireflies\n- **Lumen**: Volumetric fog + emissive flora — shadow/light weaving puzzles.\n- **Data Layer**: DL_Canopy (densest streaming, HLOD 3 levels)\n",
 "Content/World/Shared/PCG_RiftCracks.md": "# PCG — Rift Cracks\n\nGraph: PCG_RiftCracks (WP_RiftWeave)\n- Input: Spline + DataLayer mask\n- Nodes: SurfaceSampler -> Noise (crack) -> Prune by slope -> StaticMeshSpawner (SM_RiftCrack_*)\n- Nanite meshes: SM_RiftCrack_A/B/C (2k-8k tris, Nanite yes)\n- Perf: 4000 instances per km2, culling 80m\n",
 "Content/Audio/MetaSounds/README.md": "# MetaSounds\n\n- **MS_Loom_Base**: Quartz-clocked hum; inputs: Stability (0-1), BiomeBlend, WeaveTrigger\n- **MS_Biome_Ambience**: Three layers crossfaded by UDimensionManager weights.\n- **MS_UI_Stability**: Granular ping pitch-shifts with stability\n\nAll driven via UMetaSoundWeaveController. No static BGM — dynamic.\n",
 "Content/Niagara/README.md": "# Niagara Systems\n\n- **NS_WeaveTear**: Ribbon + mesh tear, Substrate seam glow\n- **NS_StitchWeld**: Weld sparks, driven by WeaveComponent.Stability\n- **NS_BiomeBlend**: Per-biome fog lerps on dimension weight\n- **NS_PhotoConfetti**: Photo Mode 2s burst on auto-capture\n",
 "Content/UI/README.md": "# UI — CommonUI\n\n- **WBP_HUD_Stability**: Ring (180°, 0-100%), anchor pips (1-4)\n- **WBP_LoomWorkshop**: Pattern grid, 3D preview viewport\n- **WBP_PhotoMode**: Rule-of-thirds grid + share\n- **Style**: Woven-thread motif. Colors: obsidian #1A1A1E, frost #E6F7FF, canopy #1BFF8A\n",
 "Content/Maps/README.md": "# Maps\n\n- **L_Lobby**: Persistent lobby — loom tutorial, matchmaking (EOS)\n- **WP_RiftWeave**: World Partition 16km2, three DataLayers + HLOD\n- **Test_Mass_2000**: MassAI perf test (2k elk, 500 drones)\n",
}
for p,c in contents.items():
    full = base / p
    full.parent.mkdir(parents=True, exist_ok=True)
    full.write_text(c, encoding="utf-8")
    print(f"wrote {p}")

# targets
(base / "Source/RiftWeave.Target.cs").write_text("using UnrealBuildTool;\npublic class RiftWeaveTarget : TargetRules {\n    public RiftWeaveTarget(TargetInfo Target):base(Target){\n        Type=TargetType.Game;\n        DefaultBuildSettings=BuildSettingsVersion.V5;\n        IncludeOrderVersion=EngineIncludeOrderVersion.Latest;\n        ExtraModuleNames.AddRange(new[]{\"RiftWeave\"});\n    }\n}\n", encoding="utf-8")
(base / "Source/RiftWeaveEditor.Target.cs").write_text("using UnrealBuildTool;\npublic class RiftWeaveEditorTarget : TargetRules {\n    public RiftWeaveEditorTarget(TargetInfo Target):base(Target){\n        Type=TargetType.Editor;\n        DefaultBuildSettings=BuildSettingsVersion.V5;\n        IncludeOrderVersion=EngineIncludeOrderVersion.Latest;\n        ExtraModuleNames.AddRange(new[]{\"RiftWeave\"});\n    }\n}\n", encoding="utf-8")
print("content done")
